### ISSUE TITLE
Unable To Occupy

### ISSUE THREAD

**Issue by ZKing994** [tomiichx/tomic_territories#1]
The framework I'm using is: 
[https://github.com/esx-framework](url)
and the "rprogress" script is installed

Although I changed the prefix of the script name, but I use the original script without changing the name, the following problems still occur 👇

When starting to occupy, F8 prompts the following:
SCRIPT ERROR: @esx_territories/client.lua:679: attempt to compare table with number
![20230206141729](https://user-images.githubusercontent.com/82860645/216900443-0ab7f51d-08e3-4402-a209-879605ba8457.png)
![image](https://user-images.githubusercontent.com/82860645/216900870-bee12f49-bc83-4b3b-84e0-05b3195d6b0b.png)

video preview:
[https://fiverr-res.cloudinary.com/video/upload/t_fiverr_hd/v1/video-secured-attachments/messaging_message/attachment/a919fb0efb42d9848d918f053c486567-1675661018858/bandicam%202023-02-06%2013-17-02-998?__cld_token__=exp=1675687064~hmac=c6b24272088d76b1bb14086775c6cb046c7ae3b84299fb0114d962a27297698a](url)

I don't know what causes this error, I can't figure it out, does the author know the reason? @tomiichx

**Comment by tomiichx** [comment]
Hi, thanks for addressing the issue here!

A lot of servers are using the script, and this is the first time I'm seeing this, so I'm not entirely sure what is going on. Since I'm kind of busy right now, I can't debug it, but I can maybe help you get through this.

You are comparing something with a number (60 in this case), and progress would be 0 by default, so an integer that is defined all the way at the top. Could you screenshot the top of the client, maybe you deleted or adjusted some variables?

FYI: The script is getting a rework in the following days (will use a better logic for this and avoid nesting these if statements), and I will definitely look into this.

**Comment by tomiichx** [comment]
> 
> You are comparing something with a number (60 in this case), and progress would be 0 by default, so an integer that is defined all the way at the top. Could you screenshot the top of the client, maybe you deleted or adjusted some variables?
> 

This would basically mean that you have progress = {} on top, and not progress = 0.

**Comment by ZZG994521** [comment]
> 

`ESX = exports['es_extended']:getSharedObject()
local --[[ ESX,  ]]PlayerData, territoriesClient, Blips, iBlips, progress, isTaking = nil, {}, {}, {}, {}, 0, false

CreateThread(function()
    --while ESX == nil do TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end) Wait(250) end
    while ESX.GetPlayerData().job == nil do Wait(250) end
    PlayerData = ESX.GetPlayerData()
end)

RegisterNetEvent('esx:playerLoaded')
AddEventHandler('esx:playerLoaded', function(xPlayer)
    PlayerData = xPlayer
end)

RegisterNetEvent('esx:setJob')
AddEventHandler('esx:setJob', function(job)
    PlayerData.job = job
end)

CreateThread(function()
    ESX.TriggerServerCallback('esx_territories:getTerritories', function(territories) 
        territoriesClient = territories
    end)
    Wait(1000)
    createBlips()
end)

RegisterNetEvent('esx_territories:updateTerritories')
AddEventHandler('esx_territories:updateTerritories', function(territories)
    territoriesClient = territories
    for i, blipovi in pairs(iBlips) do
        RemoveBlip(blipovi)
    end
    iBlips = {}
    for i, blipovix in pairs(Blips) do
        RemoveBlip(blipovix)
    end
    Blips = {}
    Wait(1000)
    createBlips()
end)

RegisterNetEvent('esx_territories:blipblink')
AddEventHandler('esx_territories:blipblink', function(id, job, label)
    while true do
        Wait(1000)
        for i, v in pairs(territoriesClient) do
            if v.id == id then
                if v.isTaking then
                    for k, p in pairs(shared.gangs) do
                        if v.owner == k then
                            SetBlipColour(iBlips[i], p.blipboja)
                            Wait(1000)
                            SetBlipColour(iBlips[i], shared.gangs[job].blipboja)
                        end
                    end
                else
                    break
                end
            end
        end
    end
end)

RegisterNetEvent('esx_territories:createTerritory')
AddEventHandler('esx_territories:createTerritory', function()
    local player = PlayerPedId()
    local coords = GetEntityCoords(player)
    local input = lib.inputDialog('创建一个新领地', {
        { type = 'input', label = '领地名称' },
        { type = 'input', label = '领地半径' },
        { type = 'select', label = '领地类型', options = {
            { value = 'market', label = '进口' },
            { value = 'dealer', label = '出口' },
            { value = 'default', label = '洗钱' },
        }},
    })
    if input then
        if input[1] ~= nil and tonumber(input[2]) ~= nil and input[3] ~= nil then
            local name = input[1]
            local radius = input[2]
            local type = input[3]
            local territoryInfo = {
                id = #territoriesClient +1,
                name = name,
                type = type,
                owner = 'noone',
                label = '无',
                radius = radius,
                isTaking = false,
                progress = 0,
                cooldown = false,
                coords = coords,
            }
            TriggerServerEvent('esx_territories:createTerritory', territoryInfo)
        else
            ESX.ShowNotification('您必须正确填写所有字段!')
        end
    else
        ESX.ShowNotification('您取消了创建新领地.')
    end
end)

RegisterNetEvent('esx_territories:deleteTerritory')
AddEventHandler('esx_territories:deleteTerritory', function()
    local player = PlayerPedId()
    local coords = GetEntityCoords(player)
    local input = lib.inputDialog('移除一个领地', {
        { type = 'input', label = '领地名称' },
    })
    if input then
        if input[1] ~= nil then
            local name = input[1]
            TriggerServerEvent('esx_territories:deleteTerritory', name)
        else
            ESX.ShowNotification('您必须正确填写所有字段!')
        end
    else
        ESX.ShowNotification('您取消了创建新领地.')
    end
end)

createBlips = function()
    for i = 1, #territoriesClient, 1 do
        local info = territoriesClient[i]
        vlasnik = info.owner
        label = info.label
        pocetnoslovo = string.upper(string.sub(vlasnik, 1, 1))
        ostatak = string.sub(vlasnik, 2)
        local blipovi = AddBlipForCoord(info.coords.x, info.coords.y, info.coords.z) -- T1
        SetBlipSprite(blipovi, 391)
        SetBlipDisplay(blipovi, 8)
        SetBlipScale(blipovi, 1.0)
        for k, v in pairs(shared.gangs) do
            if info.owner == k then
                SetBlipColour(blipovi, v.blipboja)
            end
        end
        SetBlipAlpha(blipovi, 100)
        SetBlipAsShortRange(blipovi, true)
        table.insert(iBlips, blipovi)
        -- Kostur Blipovi // Skull Blips
        local blipovix = AddBlipForCoord(info.coords.x, info.coords.y, info.coords.z + 15) -- T1
        SetBlipSprite(blipovix, 391)--162
        SetBlipDisplay(blipovix, 4)
        BeginTextCommandSetBlipName('STRING')
        if info.owner ~= 'noone' then
            AddTextComponentString('领地: '..info.name..' | 实际掌控者: '..info.label..'')
        else
            AddTextComponentString('领地: '..info.name..' | 无人占领!')
        end
        EndTextCommandSetBlipName(blipovix)
        SetBlipScale(blipovix, 0.0)
        for k, v in pairs(shared.gangs) do
            if info.owner == k then
                SetBlipColour(blipovix, v.blipboja)
            end
        end
        --SetBlipColour(blipovix, 0)
        SetBlipAlpha(blipovix, 250)
        SetBlipAsShortRange(blipovix, true)
        table.insert(Blips, blipovix)
    end
end

-- e.g | PomocniText('Press ~INPUT_CONTEXT~ to do something!')
-- Good way to replace the default ESX Show Help Notification...
PomocniText = function(tekst)
    SetTextComponentFormat('STRING')
    AddTextComponentString(tekst)
    DisplayHelpTextFromStringLabel(0, 0, 1, -1)
end

CreateThread(function()
    Wait(1000)
    local showUI
    while true do
        Wait(0)
        local playerPed = PlayerPedId()
        local spavaj = true
        local playerCoords = GetEntityCoords(playerPed)
        for k, v in pairs(territoriesClient) do
            local coords = vec3(v.coords.x, v.coords.y, v.coords.z)
            local coordsx = vec3(v.coords.x, v.coords.y, v.coords.z-17.0)
            local distance = #(playerCoords - coords)
            if PlayerData.job and shared.gangs[PlayerData.job.name] then
                if distance < tonumber(v.radius) then
                    spavaj = false
                    DrawMarker(2, coords, 0.0, 0.0, 0.0, 0.0, 0, 0.0, 0.15, 0.15, 0.15, 200, 0, 50, 230, true, true, 2, true, false, false, false)
                    DrawMarker(1, coords, 0.0, 0.0, 0.0, 0.0, 0, 0.0, 0.25, 0.25, 0.02, 255, 255, 255, 255, false, true, 1, true, false, false, false)
                    territorydata = {
                        id = v.id,
                        job = PlayerData.job.name,
                        label = PlayerData.job.label,
                        name = v.name,
                        currentOwner = v.owner,
                        crds = vec3(v.coords.x, v.coords.y, v.coords.z),
                        taking = v.isTaking,
                        cooldown = v.cooldown,
                        type = v.type,
                        spawnano = v.spawnano,
                        radi = v.radi
                    }
                    if distance < 1.5 then
                        if IsControlJustPressed(0, 38) then
                            TriggerEvent('esx_territories:infoMeni', territorydata)
                        end
                        if showUI ~= 0 then
                            lib.showTextUI('[E] - 信息 | '..territorydata.name..'')
                        elseif showUI ~= 0 and distance > 2.0 then
                            showUI = nil
                            lib.hideTextUI()
                        end
                    elseif distance > 2.0 then
                        showUI = nil
                        lib.hideTextUI()
                    end
                end
            end
        end
        if spavaj then Wait(1337) end
    end
end)

RegisterNetEvent('esx_territories:infoMeni')
AddEventHandler('esx_territories:infoMeni', function(territorydata)
    if territorydata.type == 'dealer' then
        lib.registerContext({
            id = 'infoMeniDealer',
            title = '领地: '..territorydata.name..' | 🎲',
            options = {
                {
                    title = '占领 | 🚩',
                    event = 'esx_territories:pokreni',
                    metadata = {
                        '按下按钮开始占领领地: '..territorydata.name..'!',
                    },
                    args = {
                        x = territorydata
                    }
                },
                {
                    title = '领地库存 | 📦',
                    event = 'esx_territories:openStash',
                    metadata = {
                        '访问领地库存 '..territorydata.name..'.',
                    },
                    args = {
                        x = territorydata
                    }
                },
                {
                    title = '出口商品 | 💸',
                    event = 'esx_territories:listaItema',
                    args = {
                        data = territorydata
                    }
                },
            }
        })
        lib.showContext('infoMeniDealer')
    elseif territorydata.type == 'market' then
        lib.registerContext({
            id = 'infoMeniMarket',
            title = '领地: '..territorydata.name..' | 🎲',
            options = {
                {
                    title = '占领 | 🚩',
                    event = 'esx_territories:pokreni',
                    metadata = {
                        '按下按钮开始占领领地: '..territorydata.name..'!',
                    },
                    args = {
                        x = territorydata
                    }
                },
                {
                    title = '领地库存 | 📦',
                    event = 'esx_territories:openStash',
                    metadata = {
                        '访问领地库存 '..territorydata.name..'.',
                    },
                    args = {
                        x = territorydata
                    }
                },
                {
                    title = '进口商品 | 🛒',
                    event = 'esx_territories:BuyList',
                    args = {
                        data = territorydata
                    }
                },
            }
        })
        lib.showContext('infoMeniMarket')
        -- Work in progress!
    -- elseif territorydata.type == 'drugs' then
    --     lib.registerContext({
    --         id = 'infoMeniDroga',
    --         title = '领地: '..territorydata.name..' | 🎲',
    --         options = {
    --             {
    --                 title = '占领 | 🚩',
    --                 event = 'esx_territories:pokreni',
    --                 metadata = {
    --                     '按下按钮开始占领领地: '..territorydata.name..'!',
    --                 },
    --                 args = {
    --                     x = territorydata
    --                 }
    --             },
    --             {
    --                 title = '领地库存 | 📦',
    --                 event = 'esx_territories:openStash',
    --                 metadata = {
    --                     '访问领地库存 '..territorydata.name..'.',
    --                 },
    --                 args = {
    --                     x = territorydata
    --                 }
    --             },
    --             {
    --                 title = 'Burrito Meth | 🛒',
    --                 event = 'esx_territories:burritoMeth',
    --                 args = {
    --                     data = territorydata
    --                 }
    --             },
    --         }
    --     })
    --     lib.showContext('infoMeniDroga')
    -- Work in progress!
    elseif territorydata.type == 'default' then
        lib.registerContext({
            id = 'infoMeni',
            title = '领地: '..territorydata.name..' | 🎲',
            options = {
                {
                    title = '占领 | 🚩',
                    event = 'esx_territories:pokreni',
                    metadata = {
                        '按下按钮开始占领领地: '..territorydata.name..'!',
                    },
                    args = {
                        x = territorydata
                    }
                },
                {
                    title = '领地库存 | 📦',
                    event = 'esx_territories:openStash',
                    metadata = {
                        '访问领地库存 '..territorydata.name..'.',
                    },
                    args = {
                        x = territorydata
                    }
                },
            }
        })
        lib.showContext('infoMeni')
    end
end)

-- Work in progress!
RegisterNetEvent('esx_territories:burritoMeth')
AddEventHandler('esx_territories:burritoMeth', function(data)
    infoX = data
    if data.data.spawnano == false then
        local spawnpoint = ESX.Game.IsSpawnPointClear(data.data.crds, 5.0)
        local closestPlayer, closestPlayerDistance = ESX.Game.GetClosestPlayer()
        local vozilo
        if spawnpoint then
            if closestPlayer == -1 or closestPlayerDistance > 3.0 then
                ESX.ShowNotification('没有人靠近. 你还需要一个人来开始任务!')
            else
                ESX.Game.SpawnVehicle('burrito', data.data.crds-4.0, 50.0, function(vehicle)
                    vozilo = vehicle
                    ESX.Game.SetVehicleProperties(vozilo, {
                        plate = 'METH',
                        dirtLevel = 0.0,
                        fuelLevel = 100.0,
                        color1 = 0,
                        color2 = 2,
                        modArmor = 4
                    })
                end)
                local radi = data.data.radi
                local showUIx
                while not radi do
                    Wait(0)
                    local closestVeh, distance = ESX.Game.GetClosestVehicle()
                    if distance < 7 then
                        if IsControlJustPressed(0, 38) then
                            TaskWarpPedIntoVehicle(PlayerPedId(), vozilo, 1)
                            TriggerServerEvent('esx_territories:MethServer', infoX, vozilo)
                            break
                        end
                        if showUIx ~= 0 then
                            lib.showTextUI('[E] - To Enter!')
                        elseif showUIx ~= 0 and IsPedInAnyVehicle(PlayerPedId(), false) then
                            showUIx = nil
                            lib.hideTextUI()
                        end
                    elseif IsPedInAnyVehicle(PlayerPedId(), false) then
                        showUIx = nil
                        lib.hideTextUI()
                    end
                end
            end
        else
            ESX.ShowNotification('Spawnpoint is not clear!')
        end
    else
        ESX.ShowNotification('Mission has already been started!')
    end
end)

-- Work in progress!
RegisterNetEvent('esx_territories:MethClient')
AddEventHandler('esx_territories:MethClient', function(voziloInfo)
    -- local gas = 0
    -- while IsEntityInAir(voziloInfo) and gas < 60 do
    --     Wait(1000)
    --     gas = gas + 1
    --     print(gas)
    -- end

    exports.rprogress:Custom({
        Async = false,
        canCancel = false,
        cancelKey = 178,
        x = 0.5,
        y = 0.9,
        From = 0,
        To = 100,
        Duration = shared.capturing * 60000 + 500,
        Radius = 40,
        Stroke = 3,
        Cap = 'round',
        Padding = 0,
        MaxAngle = 360,
        Rotation = 0,
        Width = 300,
        Height = 40,
        ShowTimer = false,
        ShowProgress = true,
        Easing = 'easeLinear',
        Label = 'Cooking meth...',
        LabelPosition = 'left',
        Color = 'rgba(255, 255, 255, 1.0)',
        BGColor = 'rgba(0, 0, 0, 0.4)',
        ZoneColor = 'rgba(51, 105, 30, 1)',
        DisableControls = {
            Mouse = true,
            Player = true,
            Vehicle = true
        },
        onStart = function()

        end,
        onComplete = function(cancelled)
            while true do
                Wait(2000)
                local uvozilu = IsPedInAnyVehicle(PlayerPedId(), true)
                if cancelled then
                    exports.rprogress:Stop()
                else
                    exports.rprogress:Stop()
                end
            end
        end
    })
end)

RegisterNetEvent('esx_territories:listaItema')
AddEventHandler('esx_territories:listaItema', function(data)
    local itemList = {}
    if PlayerData.job.name == data.data.currentOwner then
        for k, v in pairs(shared.itemsToSell) do
            local currentItemInfo = shared.itemsToSell
            local item = k
            local label = v.label
            local price = v.worth
            local black = v.black
            itemList[item] = {
                title = v.label,
                description = '💸 | 价格: $'..v.worth,
                event = 'esx_territories:letCount',
                args = {
                    selected = {
                        name = label,
                        key = item,
                        worth = price,
                        moneytype = black
                    },
                    datax = data
                }
            }
        end
        lib.registerContext({
            id = 'itemListaX',
            title = '出售',
            options = itemList,
            menu = 'infoMeniDealer'
        })
        lib.showContext('itemListaX')
    else
        ESX.ShowNotification('你不拥有这个领地!')
    end
end)

RegisterNetEvent('esx_territories:letCount')
AddEventHandler('esx_territories:letCount', function(selected, datax)
    local input = lib.inputDialog(selected.selected.name, {'Amount'})
    if input then
        local count = tonumber(input[1])
        if count < 1 then
            return ESX.ShowNotification('金额不能小于 1!')
        else
            allInfo = {
                i = selected.selected.key,
                ime = selected.selected.name,
                xCount = count,
                xWorth = selected.selected.worth,
                xType = selected.selected.moneytype
            }
            TriggerServerEvent('esx_territories:sellDealer', allInfo)
        end
    end
end)

RegisterNetEvent('esx_territories:BuyList')
AddEventHandler('esx_territories:BuyList', function(data)
    local buyList = {}
    if PlayerData.job.name == data.data.currentOwner then
        for k, v in pairs(shared.itemsToBuy) do
            local item = k
            local label = v.label
            local price = v.worth
            local black = v.black
            buyList[item] = {
                title = v.label,
                description = '💸 | 价格: $'..v.worth,
                event = 'esx_territories:buyCount',
                args = {
                    selected = {
                        name = label,
                        key = item,
                        worth = price,
                        moneytype = black
                    },
                    datax = data
                }
            }
        end
        lib.registerContext({
            id = 'buyList',
            title = '购买',
            options = buyList,
            menu = 'infoMeniMarket'
        })
        lib.showContext('buyList')
    else
        ESX.ShowNotification('你不拥有这个领地!')
    end
end)

RegisterNetEvent('esx_territories:buyCount')
AddEventHandler('esx_territories:buyCount', function(selected, datax)
    local input = lib.inputDialog(selected.selected.name, {'Amount'})
    if input then
        local count = tonumber(input[1])
        if count < 1 then
            return ESX.ShowNotification('金额不能小于 1!')
        else
            allInfo = {
                i = selected.selected.key,
                ime = selected.selected.name,
                xCount = count,
                xWorth = selected.selected.worth,
                xType = selected.selected.moneytype
            }
            TriggerServerEvent('esx_territories:buyMarket', allInfo)
        end
    end
end)

RegisterNetEvent('esx_territories:pokreni')
AddEventHandler('esx_territories:pokreni', function(x)
    if territorydata.job ~= territorydata.currentOwner then
        if territorydata.taking == false then
            if territorydata.cooldown == false then
                TriggerServerEvent('esx_territories:capturestart', territorydata.id, territorydata.job, territorydata.label, territorydata.name, territorydata.currentOwner)
            else
                ESX.ShowNotification('该领地最近被占领或试图占领!')
            end
        else
            ESX.ShowNotification('有人已经在占领领地!')
        end
    else
        ESX.ShowNotification('这片领地已经属于你!')
    end
end)

RegisterNetEvent('esx_territories:openStash')
AddEventHandler('esx_territories:openStash', function(x)
    local igrac = PlayerPedId()
    local kordinateigraca = GetEntityCoords(igrac)
    local distanca = #(territorydata.crds - kordinateigraca)
    if distanca < 5.0 then
        if PlayerData.job and PlayerData.job.name == territorydata.currentOwner then
            exports.ox_inventory:openInventory('stash', {id = '['..territorydata.name..']['..territorydata.id..']'})
        else
            ESX.ShowNotification('你不拥有这个领地!')
        end
    end
end)

RegisterNetEvent('esx_territories:progressBars')
AddEventHandler('esx_territories:progressBars', function(type)
    if type == 'start' then
        exports.rprogress:Custom({
            Async = false,
            canCancel = false,
            cancelKey = 178,
            x = 0.5,
            y = 0.9,
            From = 0,
            To = 100,
            Duration = shared.capturing * 60000 + 500,
            Radius = 40,
            Stroke = 3,
            Cap = 'round',
            Padding = 0,
            MaxAngle = 360,
            Rotation = 0,
            Width = 300,
            Height = 40,
            ShowTimer = false,
            ShowProgress = true,
            Easing = 'easeLinear',
            Label = 'Capturing...',
            LabelPosition = 'right',
            Color = 'rgba(255, 0, 0, 1.0)',
            BGColor = 'rgba(0, 0, 0, 0.4)',
            ZoneColor = 'rgba(51, 105, 30, 1)',
            DisableControls = {
                Mouse = false,
                Player = false,
                Vehicle = false
            },
            onStart = function()
            end,
            onComplete = function(cancelled)
                exports.rprogress:Stop()
            end
        }
    )
    elseif type == 'stop' then
        exports.rprogress:Stop()
    end
end)

RegisterNetEvent('esx_territories:captureprogress')
AddEventHandler('esx_territories:captureprogress', function(datakey, data)
    while true do
        Wait(0)
        local playerPed = PlayerPedId()
        local playerCoords = GetEntityCoords(playerPed)
        local coords = vec3(data.coords.x, data.coords.y, data.coords.z)
        local distance = #(playerCoords - coords)
        local isDead = IsPedDeadOrDying(playerPed, true)
        lastTerritory = datakey
        prekidanje = data.radius + 1.0
        if distance < prekidanje then
            if not isDead then
                if data.isTaking == true then
                    if progress < 60 then
                        TriggerEvent('esx_territories:progressBars', 'start')
                        Wait(shared.capturing * 60000 / 60)
                        progress = progress + 1
                    else
                        TriggerEvent('esx_territories:progressBars', 'stop')
                        job = PlayerData.job.name
                        label = PlayerData.job.label
                        prvivlasnik = data.owner
                        TriggerServerEvent('esx_territories:capturecomplete', data.id, job, label, prvivlasnik)
                        progress = 0
                        TriggerEvent('esx_territories:progressBars', 'stop')
                        ESX.ShowNotification('您已成功占领 '..data.name..'!')
                        TriggerEvent('esx_territories:progressBars', 'stop')
                        break
                    end
                else
                    break
                end
            else
                TriggerEvent('esx_territories:progressBars', 'stop')
                ESX.ShowNotification('你死了, 占领进度已停止!')
                progress = 0
                TriggerServerEvent('esx_territories:captureend', lastTerritory)
                lastTerritory = nil
                break
            end
        else
            TriggerEvent('esx_territories:progressBars', 'stop')
            ESX.ShowNotification('你离开了领地, 占领进度已停止!')
            progress = 0
            TriggerServerEvent('esx_territories:captureend', lastTerritory)
            lastTerritory = nil
            break
        end
    end
end)

RegisterCommand('territories', function()
    if shared.rankings then
        lib.registerContext({
            id = 'prvastrana',
            title = 'Teritorije Meni | 🎲',
            options = {
                {
                    title = '领地列表 | 🚩',
                    event = 'esx_territories:drugastrana',
                    metadata = {
                        '所有领地.',
                    },
                },
                {
                    title = '排行榜 | 🏆',
                    event = 'esx_territories:trecastrana',
                    metadata = {
                        '显示每个帮派的领地列表及其历史积分',
                    },
                },
                -- {
                --     title = '信息 | ❓',
                --     metadata = {
                --         '| Made by Tomić ✅',
                --     },
                -- },
            }
        })
    else
        lib.registerContext({
            id = 'prvastrana',
            title = 'Teritorije Meni | 🎲',
            options = {
                {
                    title = '领地列表 | 🚩',
                    event = 'esx_territories:drugastrana',
                    metadata = {
                        '所有领地.',
                    },
                },
                -- {
                --     title = 'Info | ❓',
                --     metadata = {
                --         '| Made by Tomić ✅',
                --     },
                -- },
            }
        })
    end
    lib.showContext('prvastrana')
end)

RegisterNetEvent('esx_territories:drugastrana')
AddEventHandler('esx_territories:drugastrana', function(args)
    local libTer = {}
    if territoriesClient ~= nil then
        for i = 1, #territoriesClient, 1 do
            local info = territoriesClient[i]
            local ter = vec3(info.coords.x, info.coords.y, info.coords.z)
            local pr = nil
            local cd = nil
            local vl = info.owner
            local ps = string.upper(string.sub(vl, 1, 1))
            local os = string.sub(vl, 2)
            if info.isTaking == true then pr = 'Yes' else pr = 'No' end
            if info.cooldown == true then cd = 'Yes' else cd = 'No' end
            libTer[i] = {
                title = '💀 | 领地: '..info.name,
                description = '🚩 | 实际掌控者: '..info.label,
                metadata = {
                    '正在占领: '..pr,
                    '冷却时间: '..cd,
                },
            }
        end
        lib.registerContext({
            id = 'drugastrana',
            title = '领地列表',
            menu = 'prvastrana',
            options = libTer,
        })
        lib.showContext('drugastrana')
    end
end)

RegisterNetEvent('esx_territories:trecastrana')
AddEventHandler('esx_territories:trecastrana', function(args)
    ESX.TriggerServerCallback('esx_territories:povucipoene', function(lista)
        local trTabela = {}
        if territoriesClient ~= nil then
            for i = 1, #lista, 1 do
                table.sort(lista, function(a, b) return a.poeni > b.poeni end)
                trTabela[i] = {
                    title = '💀 | 帮派: '..lista[i].label,
                    description = '🏆 | 地位: '..i,
                    metadata = {
                        '⭐ | 历史积分: '..lista[i].poeni,
                        '⭐ | 月积分: '..lista[i].mespoeni,
                        '⭐ | 周积分: '..lista[i].nedpoeni
                    }
                }
            end
            lib.registerContext({
                id = 'trecastrana',
                menu = 'prvastrana',
                title = '排行榜',
                options = trTabela,
            })
            lib.showContext('trecastrana')
        end
    end)
end)

AddEventHandler('onResourceStop', function(resourceName)
	if resourceName == GetCurrentResourceName() then 
		TriggerEvent('esx_territories:progressBars', 'stop')
	end
end)`

**Comment by ZZG994521** [comment]
> > You are comparing something with a number (60 in this case), and progress would be 0 by default, so an integer that is defined all the way at the top. Could you screenshot the top of the client, maybe you deleted or adjusted some variables?
> 
> This would basically mean that you have progress = {} on top, and not progress = 0.

There are a total of the following four "progress = 0" in the Client.lua file:
![image](https://user-images.githubusercontent.com/82860645/216960000-e72abaf0-25db-4d06-9e39-e252473a8bae.png)
![image](https://user-images.githubusercontent.com/82860645/216960234-bd041d9a-849b-4931-a520-35f68cbd94be.png)

But, have not "progress = {}":
![image](https://user-images.githubusercontent.com/82860645/216960460-bbb1797e-8a0b-46e7-ad00-92150bda123e.png)

**Comment by ZKing994** [comment]
I got it !!!!
In the second line from the top, I only commented out the "ESX," at the beginning, but ignored the "nil," at the end, you see.👇
![image](https://user-images.githubusercontent.com/82860645/216961839-6b7ef713-949a-448b-ac7d-f2ba1356b5ca.png)
So this results in a "progress = {}" at the top like you said.

So, I should do this.👇
![image](https://user-images.githubusercontent.com/82860645/216962647-01f7599f-b7de-433a-a469-730a20dc84b1.png)


Everything is working fine!👇
![image](https://user-images.githubusercontent.com/82860645/216963723-e4a0a4e2-f3e0-4469-a34b-a21a5807bfd5.png)
Thank you very much for your guidance! Thank you!😀

**Comment by tomiichx** [comment]
Correct, good job! 😄
Have a nice day! 👍🏼
