### ISSUE TITLE
[SUGGESTION] Blips only visible for gangs

### ISSUE THREAD

**Issue by Gameadictive** [tomiichx/tomic_territories#10]
Can u make it possible? Maybe an update?

**Comment by tomiichx** [comment]
Will be updated

**Comment by tomiichx** [comment]
Commit: [796c597](https://github.com/tomiichx/tomic_territories/commit/796c597)

**Comment by Gameadictive** [comment]
Blips should be appear or dissapear if u have or not the gang job.

Instead even if u abandon the gang seeing the blips u will still seeing the blips until server restart. Can u fix it?
