### ISSUE TITLE
Any way to get it working with esx gangs and not job ?

### ISSUE THREAD

**Issue by Arcticguy867** [tomiichx/tomic_territories#8]
Get it working with esx_gangs (https://forum.cfx.re/t/esx-gangs-gang-turf-wars/2177263?page=2)

The gang system with this rather than jobs

**Comment by tomiichx** [comment]
Hello there,

This script is supposed to work with latest ESX Legacy, as well as it's resouces along with Overextended scripts. This resource is not going to be adjusted to some third party scripts. Also, the provided script is really old, and definitely shouldn't be used.
In case you want something similar, better performant and simpler, you can use 'esxbalkan_mafije' which works perfectly with my territories. They provide everything you need. It's job-based which makes it compatible with any ESX resource.

Thank you,
Have a nice day.
